### ISSUE TITLE
I cannot drag a group

### ISSUE THREAD

**Issue by tobiascapin** [meszaros-lajos-gyorgy/raphael-plugin-group#8]
I saw that there is a draggable function but I could not drag a group. Can you please add an example?
I tried this:

`group.drag(movf,startf,endf)`

**Comment by meszaros-lajos-gyorgy** [comment]
I updated the demo page (demo/group.html), where you can test out the dragging functionality.

You only need to call ```group.draggable()``` to make it draggable. You can also read and update the dragspeed, which is done by calling ```<float> = group.getDragSpeed()``` and ```group = group.setDragSpeed(<float>)```

Please note, that once you make a group draggable, you cannot undo it, only bypass it by setting the drag speed to 0.

Another note: if you transform the object, then the speed will not seem to match, might need an update on that in a later update.
